import absoluteUrl from 'next-absolute-url'

export default async (req, res) => {
  const { origin } = absoluteUrl(req)
  if (req.method === "GET") {
    res.statusCode = 200;
    res.setHeader("Content-Type", "application/xml");
    res.send(`<?xml version="1.0" encoding="UTF-8"?>
        <?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
        <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url>
		<loc>${origin}/blog/</loc>
		<lastmod>2023-01-20T10:59:15+00:00</lastmod>
	</url>
	<url>
		<loc>${origin}/blog/importance-of-video-and-customer-review-for-automotive-industry/</loc>
		<lastmod>2022-11-09T10:43:55+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog6_img1.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/how-to-manage-an-auto-repair-mechanic-shop/</loc>
		<lastmod>2022-11-09T10:52:46+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog8_img1.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/how-software-will-benefits-the-automotive-industry/</loc>
		<lastmod>2022-11-09T11:01:27+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog9_img1.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/tips-to-improve-customer-service-for-your-automotive-shop/</loc>
		<lastmod>2022-11-09T11:03:37+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog10_img1.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/reasons-why-garages-need-an-automotive-software/</loc>
		<lastmod>2022-11-09T11:15:54+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog11_img1.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/how-will-your-auto-shop-get-more-profit-from-mobile-mechanics/</loc>
		<lastmod>2022-11-09T11:22:33+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog12_img1.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/benefits-of-mobile-app-for-automotive-business/</loc>
		<lastmod>2022-11-09T11:30:01+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog13_img1.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/soft-skills-for-the-automotive-technician/</loc>
		<lastmod>2022-11-09T11:33:04+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog14_img1.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/types-of-software-in-automotive-and-automobile-industries/</loc>
		<lastmod>2022-11-09T11:50:12+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog16_img1.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/benefits-of-using-5iq-customer-app/</loc>
		<lastmod>2022-11-09T12:24:26+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog17_img1.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2020/06/5iq-customer-app.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/automotive-software-development-trends/</loc>
		<lastmod>2022-11-09T12:26:58+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_18.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/customer-vehicle-details-management-with-5iq/</loc>
		<lastmod>2022-11-09T12:35:27+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog19_img1.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog19_img2.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog19_img3.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog19_img4.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/mobile-payments-in-automotive-industry/</loc>
		<lastmod>2022-11-09T12:45:31+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog20_img1.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/5iq-software-listed-in-goodfirms/</loc>
		<lastmod>2022-11-09T12:56:47+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog21_img1.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/how-to-use-5iq-digital-inspection-feature/</loc>
		<lastmod>2022-11-09T13:17:01+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog23_img1.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog23_img2.jpg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog23_img3.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/how-to-get-more-customers-to-your-auto-repair-shop/</loc>
		<lastmod>2022-11-09T13:21:24+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_25.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/ways-to-increase-productivity-at-your-auto-repair-shop/</loc>
		<lastmod>2022-11-09T13:24:07+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_27.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/safety-rules-for-automotive-repair-shops/</loc>
		<lastmod>2022-11-09T13:26:09+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_28.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/what-is-a-digital-vehicle-inspection/</loc>
		<lastmod>2022-11-09T13:30:44+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_29.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/how-to-choose-the-right-automotive-software-for-your-auto-shop/</loc>
		<lastmod>2022-11-09T13:33:10+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_30.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/tips-to-expand-your-auto-repair-shop/</loc>
		<lastmod>2022-11-09T13:36:26+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_31.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/advantage-of-using-5iq-workshop-software-during-pandemic/</loc>
		<lastmod>2022-11-23T13:13:07+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_24.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog24_img1.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/customer-information-and-asset-management-with-5iq-auto-crm-software/</loc>
		<lastmod>2022-11-23T13:21:02+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog15_img1.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog15_img4.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog15_img3.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog15_img2.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog15_img5.png</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/automotive-software-for-mechanical-industries/</loc>
		<lastmod>2023-01-20T10:38:36+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_3.jpg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_3.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/top-automotive-industry-trends/</loc>
		<lastmod>2023-01-20T10:42:15+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_4.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img2.jpg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img3.jpg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img5.jpeg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img1.jpg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img4.jpg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img7.jpg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img8.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img8-1.png</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img10.jpg</image:loc>
		</image:image>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog4_img11.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/which-software-does-your-automotive-shop-require/</loc>
		<lastmod>2023-01-20T10:43:00+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog_banner_5.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/tips-for-automotive-business-to-better-communicate-with-the-customers/</loc>
		<lastmod>2023-01-20T10:44:04+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog7_img1.jpg</image:loc>
		</image:image>
	</url>
	<url>
		<loc>${origin}/blog/digital-system-benefits-for-automotive-businesses/</loc>
		<lastmod>2023-01-20T10:56:04+00:00</lastmod>
		<image:image>
			<image:loc>https://rcreators.in/5iq/wp-content/uploads/2022/11/blog22_img1.png</image:loc>
		</image:image>
	</url>
</urlset>
      `);
  } else {
    // Handle any other HTTP method
  }
};
